
services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3
    container_name: traefik
    ports:
      # The HTTP port
      - 80:80
      # web secure port
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # mount traefik config and make it read only
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/traefik-dynamic.yaml:/etc/traefik/traefik-dynamic.yaml:ro
    # connect to backend network
    networks:
      - backend
    labels:
      traefik.enable: 'true'
    restart: unless-stopped
networks:
  backend:
    # using existing netoworks
    external: true
